#!/bin/bash

timedatectl set-ntp true
echo -e "o\nn\n\n\n\n+4g\nn\n\n\n\n\nt\n1\n82\na\n2\nw\nq\n"|sudo fdisk /dev/sda
mkfs.ext4 /dev/sda2
mkswap /dev/sda1
mount /dev/sda2 /mnt
pacstrap /mnt base
echo "# 
# /etc/fstab: static file system information
#
# <file system>	<dir>	<type>	<options>	<dump>	<pass>
UUID=$(lsblk -no UUID /dev/sda2)         	ext4      	rw,relatime,data=ordered	0 1
UUID=$(lsblk -no UUID /dev/sda1)	none		swap		defaults			0 0
" > /mnt/etc/fstab
echo 'ln -sf /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "KEYMAP=dk" >> /etc/vconsole.conf
locale-gen
echo "jannick" > /etc/hostname
echo "127.0.0.1 jannick.localdomain jannick" > /etc/hosts
pacman -S networkmanager
systemctl enable NetworkManager
pacman -S grub
grub-install --target=i386-pc /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg' > /mnt/install_arch
chmod +x /mnt/install_arch
echo "./install_arch"|arch-chroot /mnt

umount -R /mnt
echo done
